# Generated by Django 3.2 on 2021-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
