# Generated by Django 3.2 on 2021-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.CharField(max_length=120),
        ),
    ]
